name: tag

on:
  push:
    tags:
      - 'v*.*.*'

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build --warning-mode all
      - uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: app/build/outputs/apk/release/app-release-unsigned.apk
          draft: false
          prerelease: false
